// Mock para @notifee/react-native en Jest
const mockNotifee = {
  createChannel: jest.fn(() => Promise.resolve('channel-id')),
  deleteChannel: jest.fn(() => Promise.resolve()),
  displayNotification: jest.fn(() => Promise.resolve('notification-id')),
  cancelNotification: jest.fn(() => Promise.resolve()),
  cancelAllNotifications: jest.fn(() => Promise.resolve()),
  cancelTriggerNotifications: jest.fn(() => Promise.resolve()),
  getTriggerNotificationIds: jest.fn(() => Promise.resolve([])),
  getTriggerNotifications: jest.fn(() => Promise.resolve([])),
  createTriggerNotification: jest.fn(() => Promise.resolve('notification-id')),
  requestPermission: jest.fn(() => Promise.resolve({ authorizationStatus: 1 })),
  checkPermissions: jest.fn(() => Promise.resolve({ authorizationStatus: 1 })),
  openSettings: jest.fn(() => Promise.resolve()),
  setNotificationCategories: jest.fn(() => Promise.resolve()),
  getNotificationCategories: jest.fn(() => Promise.resolve([])),
  getInitialNotification: jest.fn(() => Promise.resolve(null)),
  onForegroundEvent: jest.fn(() => jest.fn()),
  onBackgroundEvent: jest.fn(() => jest.fn()),
  isChannelCreated: jest.fn(() => Promise.resolve(true)),
  isChannelBlocked: jest.fn(() => Promise.resolve(false)),
  getChannels: jest.fn(() => Promise.resolve([])),
  getChannel: jest.fn(() => Promise.resolve(null)),
  getBadgeCount: jest.fn(() => Promise.resolve(0)),
  setBadgeCount: jest.fn(() => Promise.resolve()),
  incrementBadgeCount: jest.fn(() => Promise.resolve()),
  decrementBadgeCount: jest.fn(() => Promise.resolve()),
  cancelDisplayedNotification: jest.fn(() => Promise.resolve()),
  cancelTriggerNotification: jest.fn(() => Promise.resolve()),
  getDisplayedNotifications: jest.fn(() => Promise.resolve([])),
  registerForegroundService: jest.fn(() => Promise.resolve()),
  unregisterForegroundService: jest.fn(() => Promise.resolve()),
  stopForegroundService: jest.fn(() => Promise.resolve()),
  getBatteryOptimizationStatus: jest.fn(() => Promise.resolve({ status: 0 })),
  openBatteryOptimizationSettings: jest.fn(() => Promise.resolve()),
  getPowerManagerInfo: jest.fn(() => Promise.resolve({})),
  openPowerManagerSettings: jest.fn(() => Promise.resolve()),
  getNotificationSettings: jest.fn(() => Promise.resolve({})),
  openNotificationSettings: jest.fn(() => Promise.resolve()),
  getNotificationChannelSettings: jest.fn(() => Promise.resolve({})),
  openNotificationChannelSettings: jest.fn(() => Promise.resolve()),
  openAlarmPermissionSettings: jest.fn(() => Promise.resolve()),
  getAlarmManager: jest.fn(() => Promise.resolve({})),
  setNotificationChannelGroup: jest.fn(() => Promise.resolve()),
  getNotificationChannelGroup: jest.fn(() => Promise.resolve(null)),
  getNotificationChannelGroups: jest.fn(() => Promise.resolve([])),
  deleteNotificationChannelGroup: jest.fn(() => Promise.resolve()),
  hideNotificationDrawer: jest.fn(() => Promise.resolve()),
  areNotificationsEnabled: jest.fn(() => Promise.resolve(true)),
};

// EventType enum mock
const EventType = {
  DISMISSED: 1,
  PRESS: 2,
  ACTION_PRESS: 3,
  DELIVERED: 4,
  APP_BLOCKED: 5,
  CHANNEL_BLOCKED: 6,
  CHANNEL_GROUP_BLOCKED: 7,
  TRIGGER_NOTIFICATION_CREATED: 8,
};

module.exports = {
  __esModule: true,
  default: mockNotifee,
  EventType,
};

